-- GLEE referral + points system
-- Run this SQL in the Supabase SQL editor for the GLEE project.

create table if not exists public.referral_codes (
  id bigint generated by default as identity primary key,
  wallet_address text not null unique,
  code text not null unique,
  points bigint not null default 0 check (points >= 0),
  created_at timestamptz not null default now()
);

create index if not exists referral_codes_code_idx on public.referral_codes (code);

create table if not exists public.referral_mints (
  id bigint generated by default as identity primary key,
  transaction_hash text not null unique,
  contract_address text not null,
  minter_wallet text not null,
  referrer_wallet text not null,
  referral_code_id bigint not null references public.referral_codes(id),
  quantity integer not null check (quantity > 0),
  mint_type text not null check (mint_type in ('whitelist', 'public')),
  minter_points bigint not null check (minter_points >= 0),
  referrer_points bigint not null check (referrer_points >= 0),
  created_at timestamptz not null default now(),
  constraint referral_mints_no_self_referral check (lower(minter_wallet) <> lower(referrer_wallet))
);

create index if not exists referral_mints_minter_wallet_idx on public.referral_mints (minter_wallet);
create index if not exists referral_mints_referrer_wallet_idx on public.referral_mints (referrer_wallet);
create index if not exists referral_mints_referral_code_id_idx on public.referral_mints (referral_code_id);

alter table public.referral_codes enable row level security;
alter table public.referral_mints enable row level security;

revoke all on table public.referral_codes from anon, authenticated;
revoke all on table public.referral_mints from anon, authenticated;

grant select, insert, update on table public.referral_codes to service_role;
grant select, insert on table public.referral_mints to service_role;

grant usage, select on sequence public.referral_codes_id_seq to service_role;
grant usage, select on sequence public.referral_mints_id_seq to service_role;

create or replace function public.process_referral_mint(
  p_transaction_hash text,
  p_contract_address text,
  p_minter_wallet text,
  p_referrer_wallet text,
  p_referral_code_id bigint,
  p_quantity integer,
  p_mint_type text,
  p_minter_points bigint,
  p_referrer_points bigint
)
returns table (inserted boolean, referral_mint_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
begin
  if lower(p_minter_wallet) = lower(p_referrer_wallet) then
    raise exception 'SELF_REFERRAL_NOT_ALLOWED';
  end if;
  if p_quantity <= 0 then raise exception 'INVALID_QUANTITY'; end if;
  if p_mint_type not in ('whitelist', 'public') then raise exception 'INVALID_MINT_TYPE'; end if;
  if p_minter_points < 0 or p_referrer_points < 0 then raise exception 'INVALID_POINTS'; end if;

  insert into public.referral_mints (
    transaction_hash, contract_address, minter_wallet, referrer_wallet, referral_code_id,
    quantity, mint_type, minter_points, referrer_points
  ) values (
    lower(p_transaction_hash), lower(p_contract_address), lower(p_minter_wallet), lower(p_referrer_wallet), p_referral_code_id,
    p_quantity, p_mint_type, p_minter_points, p_referrer_points
  )
  on conflict (transaction_hash) do nothing
  returning id into new_id;

  if new_id is null then
    return query select false, null::bigint;
    return;
  end if;

  update public.referral_codes
     set points = points + p_minter_points
   where lower(wallet_address) = lower(p_minter_wallet);

  update public.referral_codes
     set points = points + p_referrer_points
   where id = p_referral_code_id
     and lower(wallet_address) = lower(p_referrer_wallet);

  return query select true, new_id;
end;
$$;

revoke all on function public.process_referral_mint(text, text, text, text, bigint, integer, text, bigint, bigint)
  from public, anon, authenticated;
grant execute on function public.process_referral_mint(text, text, text, text, bigint, integer, text, bigint, bigint)
  to service_role;
